# schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field : CAST(date_date AS TIMESTAMP)
        freshness:
          warn_after:
            count: 90
            period: day
        columns : 
          - name: date_date
            description : date of each sales operations
          - name: orders_id
            description: unique identifier code for each orders
          # test: à faire demain
      - name: product
        identifier: raw_gz_product
        description: produc ranges of Greenweez / with id_product and purchases_prices
        columns : 
          - name: products_id
            description : ids of each orders
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: details of orders and ship info for Grenweez sales / per orders we have shipping and log fees
        columns : 
          - name: orders_id
            description : ids of each orders
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: marketing campaign done with adwords / identified with campaign key
        columns : 
          - name: date_date
            description : dates of the campaign
          - name: paid_source
            description: name of the source where the campaign was done
          - name: campaign_key
            description: unique identifier code for the campaign
          - name: camPGN_name
            description: name of the campaign 
          - name: ads_cost
            description: total cost of the campaign
          - name: impression
            description: nb of impressions per campaign key 
          - name: click
            description: nb of click per campaign key 
      - name: bing
        identifier: raw_gz_bing
        description: marketing campaign done with bing / identified with campaign key
        columns : 
          - name: date_date
            description : dates of the campaign
          - name: paid_source
            description: name of the source where the campaign was done
          - name: campaign_key
            description: unique identifier code for the campaign
          - name: camPGN_name
            description: name of the campaign 
          - name: ads_cost
            description: total cost of the campaign
          - name: impression
            description: nb of impressions per campaign key 
          - name: click
            description: nb of click per campaign key 
      - name: criteo
        identifier: raw_gz_criteo
        description: marketing campaign done with criteo / identified with campaign key
        columns : 
          - name: date_date
            description : dates of the campaign
          - name: paid_source
            description: name of the source where the campaign was done
          - name: campaign_key
            description: unique identifier code for the campaign
          - name: camPGN_name
            description: name of the campaign 
          - name: ads_cost
            description: total cost of the campaign
          - name: impression
            description: nb of impressions per campaign key 
          - name: click
            description: nb of click per campaign key 
      - name: facebook
        identifier: raw_gz_facebook
        description: marketing campaign done with facebook / identified with campaign key
        columns : 
          - name: date_date
            description : dates of the campaign
          - name: paid_source
            description: name of the source where the campaign was done
          - name: campaign_key
            description: unique identifier code for the campaign
          - name: camPGN_name
            description: name of the campaign 
          - name: ads_cost
            description: total cost of the campaign
          - name: impression
            description: nb of impressions per campaign key 
          - name: click
            description: nb of click per campaign key